repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Handling unwanted unicode characters
  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes

  # Run code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.7.0 # Keep in sync with blacken-docs
    hooks:
      - id: black-jupyter

  # Format configuration files with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.1"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: ["--fix"]
